# Generated by Django 3.1.4 on 2020-12-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccomponents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpucooler',
            old_name='fan_rpm',
            new_name='max_fan_rpm',
        ),
        migrations.AddField(
            model_name='cpucooler',
            name='min_fan_rpm',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
