# Generated by Django 3.1.4 on 2020-12-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccomponents', '0002_auto_20201216_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='max_cooler_length',
        ),
        migrations.RemoveField(
            model_name='cpucooler',
            name='cooler_length',
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
