# Generated by Django 3.1.4 on 2020-12-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pccomponents', '0003_auto_20201216_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpucooler',
            name='radiator_size',
        ),
    ]
