# Generated by Django 3.1.4 on 2020-12-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pccomponents', '0004_remove_cpucooler_radiator_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpu',
            old_name='memory',
            new_name='video_memory',
        ),
    ]
