# Generated by Django 3.1.4 on 2020-12-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pccomponents', '0005_auto_20201219_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='max_ram_clock',
            new_name='max_memory_clock',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='max_ram_clock',
            new_name='max_memory_clock',
        ),
    ]
