# Generated by Django 3.1.4 on 2020-12-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccomponents', '0006_auto_20201219_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/NYCS-bull-trans-B.svg/1024px-NYCS-bull-trans-B.svg.png', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='integrated_graphics',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formfactor',
            name='formfactor_name',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='interface_name',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='memorytype',
            name='memorytype_name',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='powersupplyunit',
            name='efficiency_rating',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socket',
            name='socket_name',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
