# Generated by Django 3.1.4 on 2020-12-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pccomponents', '0007_auto_20201222_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ram',
            old_name='memory',
            new_name='module_memory',
        ),
        migrations.AddField(
            model_name='ram',
            name='memory_modules',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
