# Generated by Django 3.1.4 on 2020-12-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pccomponents', '0008_auto_20201223_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfactor',
            old_name='formfactor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='interface_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='memorytype',
            old_name='memorytype_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='socket',
            old_name='socket_name',
            new_name='name',
        ),
    ]
